apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: chatbot
spec:
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
